spring:
  datasource:
    url: jdbc:mysql://localhost:3306/postdb
    username: root
    password: temp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081